[package]
name = "somelib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[[bin]]
name = "cbindgen"
path = "build/cbindgen/main.rs"

[dependencies]

[build-dependencies]
cbindgen = "0.24"
